efi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('registration.urls')),

]

main/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^login$', auth_views.login, name='login'),
    url(r'^$', views.main_list, name='main_list'),
    url(r'^main_list$', views.main_list, name='main_list'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^ended_projects$', views.ended_projects, name='ended_projects'),
    url(r'^staged_projects$', views.staged_projects, name='staged_projects'),
    url(r'^ajax/export_table/$', views.export_table, name='export_table'),
    # url(r'^to_send$', views.to_send, name='to_send'),
    url(r'^upload/$', views.upload_file, name='upload'),
    url(r'^whole_list$', views.whole_list, name='whole_list'),
    # url(r'^table_view$', views.table_view, name='table_view'),
    url(r'^ajax/update_cell/$', views.update_cell_json, name='update_cell'),
    url(r'^ajax/stage_project/$', views.stage_project_json, name='stage_project'),
    url(r'^ajax/change_for_all_project_rows/$', views.change_for_all_project_rows, name='change_for_all_project_rows'),

    # url(r'^ajax/cancel_currency_fields/$', views.cancel_currency_fields, name='cancel_currency_fields'),

    url(r'^ajax/end_project/$', views.end_project_json, name='end_project'),
    url(r'^ajax/add_color/$', views.add_color_json, name='add_color'),
    url(r'^ajax/add_dollar/$', views.add_dollar, name='add_dollar'),
    url(r'^ajax/add_shekel/$', views.add_shekel, name='add_shekel'),
    url(r'^ajax/add_euro/$', views.add_euro, name='add_euro'),
    url(r'^test_datetime$', TemplateView.as_view(template_name="main/test_datetime.html"), name='test_datetime'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import JSONField
# https://github.com/psycopg/psycopg2/issues/329

from django.urls import reverse
#https://stackoverflow.com/questions/15454008/how-to-reset-db-in-django-i-get-a-command-reset-not-found-error
# python manage.py reset_db
# heroku pg:reset

# backups
# Asia/Jerusalem
# important!
#  https://stackoverflow.com/questions/32123477/django-revert-last-migration

# https://devcenter.heroku.com/articles/heroku-postgres-backups#creating-a-backup
# heroku pg:backups:capture --app caneti
# heroku pg:backups:restore caneti::{id - like b141} DATABASE_URL --app caneti-staging


class main_list_model(models.Model):
    # https://stackoverflow.com/questions/46343282/foreign-key-defaults-to-auth-user-in-django
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    Project_num = models.CharField(max_length=100, blank=True, null=True, verbose_name='Project number')
    Customer_num = models.CharField(max_length=100, blank=True, null=True, verbose_name='Client Reference Number')
    Customer = models.CharField(max_length=100, blank=True, null=True, verbose_name='Reference customer')
    Contact = models.CharField(max_length=100, blank=True, null=True)
    Date = models.DateField(blank=True, null=True)
    Type_of_service = models.CharField(max_length=256, blank=True, null=True)
    Type_of_car = models.CharField(max_length=256, blank=True, null=True)
    Name = models.CharField(max_length=256, blank=True, null=True, verbose_name='Name client')
    Luggage = models.CharField(max_length=10, blank=True, null=True, verbose_name='Number of PAX & Luggage')  # changed to char field

    Flight_num = models.CharField(max_length=100, blank=True, null=True)
    # changing from time field to date time field made a big problem
    # https: // stackoverflow.com / questions / 15237366 / how - to - execute - a - sql - script - on - heroku
    # https: // stackoverflow.com / questions / 23892307 / django - change - timefield - to - datetimefield - in -models - py / 39104671
    # https: // stackoverflow.com / questions / 10200769 / postgresql - column - foo - does - not -exist
    # https: // www.postgresql.org / docs / 9.1 / datatype - datetime.html
    # very importent to know!
    Flight_shcedule = models.DateTimeField(blank=True, null=True)
    Start_time = models.DateTimeField(blank=True, null=True)
    End_time = models.DateTimeField(blank=True, null=True)
    From = models.CharField(max_length=100, blank=True, null=True)
    To = models.CharField(max_length=100, blank=True, null=True)

    Provider = models.CharField(max_length=100, blank=True, null=True)
    Driver_name = models.CharField(max_length=100, blank=True, null=True)
    Provider_status = models.CharField(max_length=100, blank=True, null=True,
                                       verbose_name='Status Provider')  # new
    Comments = models.TextField(blank=True)
    Status = models.CharField(max_length=100, blank=True, null=True, verbose_name='Project Status')
    Client_status = models.CharField(max_length=100, blank=True, null=True,
                                     verbose_name='Status Client')  # new
    Extra_hours_client = models.FloatField(null=True, blank=True)
    Based_on_client = models.FloatField(blank=True, null=True)
    Extra_hours_provider = models.FloatField(null=True, blank=True)
    Based_on_provider = models.FloatField(blank=True, null=True)  # , default='09:00'

    KM = models.IntegerField(blank=True, null=True)
    Extra_KM_client = models.IntegerField(blank=True, null=True)
    Extra_KM_provider = models.IntegerField(blank=True, null=True)
    Cost_per_client = models.CharField(max_length=100, blank=True, null=True)
    Cost_per_provider = models.CharField(max_length=100, blank=True, null=True)
    Cost_transfer_client = models.CharField(max_length=100, blank=True, null=True)
    Cost_transfer_provider = models.CharField(max_length=100, blank=True, null=True)
    Cost_extra_hour_client = models.CharField(max_length=100, blank=True, null=True)
    Cost_extra_hour_provider = models.CharField(max_length=100, blank=True, null=True)
    Cost_VIP_client = models.CharField(max_length=100, blank=True, null=True)
    Cost_VIP_provider = models.CharField(max_length=100, blank=True, null=True)

    Cost_shonot_client = models.CharField(max_length=100, blank=True, null=True)
    Cost_shonot_provider = models.CharField(max_length=100, blank=True, null=True)

    Color = models.CharField(max_length=3000, blank=True, null=True)
    Canceled = models.NullBooleanField(blank=True, null=True)
    # Canceled = models.BooleanField(default=False)

    def update_field(self, key, value):
        # This will raise an AttributeError if the key isn't an attribute
        # of your model
        # https://stackoverflow.com/questions/21797436/django-how-to-update-model-field-from-json-data
        getattr(self, key)
        setattr(self, key, value)

    def __str__(self):
        return str(self.Project_num)

# class transfer(models.Model):
#
#     type_choice = (
#         ('Dep', 'Dep'),
#         ('Arr', 'Arr'),
#     )
#
#     Customer = models.CharField(max_length=100, blank=True, null=True)  # new
#     Customer_ref = models.CharField(max_length=100, blank=True, null=True)
#     Date = models.DateField(blank=True, null=True)
#     Driver = models.CharField(max_length=100, blank=True, null=True)
#     Provider = models.CharField(max_length=100, blank=True, null=True)
#     Car = models.CharField(max_length=100, blank=True, null=True)
#     Clients_Name = models.CharField(max_length=100, blank=True, null=True)
#     From = models.CharField(max_length=100, blank=True, null=True)  # new
#     To = models.CharField(max_length=100, blank=True, null=True)  # new
#     DepOrArr = models.NullBooleanField(blank=True, null=True, choices=type_choice)  # new models.NullBooleanField()
#     Flight = models.CharField(max_length=100, blank=True, null=True)
#     Time_of_flight = models.CharField(max_length=100, blank=True, null=True)  # new
#     Time_of_PU = models.CharField(max_length=100, blank=True, null=True)  # new
#     Contact = models.CharField(max_length=100, blank=True, null=True)
#     Project = models.CharField(max_length=100, blank=True, null=True)
#
#     def __str__(self):
#         return self.Customer_ref

    # def get_absolute_url(self):
    #     return reverse('transfer_update', args=(self.pk,))


class Flight_data(models.Model):  # new
    Flight = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Flight


class Customer_data(models.Model):  # new
    Customer_name = models.CharField(max_length=256, blank=True, unique=True)
    email = models.EmailField(max_length=250, blank=True, unique=False)
    phone_num = models.CharField(max_length=80, blank=True, unique=False)
    address = models.CharField(max_length=256, blank=True, unique=False)
    city = models.CharField(max_length=50, blank=True, unique=False)
    contact = models.CharField(max_length=50, blank=True, unique=False)
    id_num = models.CharField(max_length=30, blank=True, unique=False)
    used_a_lot = models.BooleanField(default=False)

    def __str__(self):
        return self.Customer_name


class Driver_data(models.Model):
    Driver = models.CharField(max_length=256, blank=True, unique=True)
    email = models.EmailField(max_length=250, blank=True, unique=False)
    phone_num = models.CharField(max_length=80, blank=True, unique=False)
    address = models.CharField(max_length=256, blank=True, unique=False)
    contact = models.CharField(max_length=50, blank=True, unique=False)
    id_num = models.CharField(max_length=30, blank=True, unique=False)

    def __str__(self):
        return self.Driver


class Provider_data(models.Model):
    Provider_name = models.CharField(max_length=256, blank=True, unique=True)
    email = models.EmailField(max_length=250, blank=True, unique=False)
    phone_num = models.CharField(max_length=80, blank=True, unique=False)
    address = models.CharField(max_length=256, blank=True, unique=False)
    city = models.CharField(max_length=100, blank=True, unique=False)
    contact = models.CharField(max_length=100, blank=True, unique=False)
    id_num = models.CharField(max_length=30, blank=True, unique=False)
    used_a_lot = models.BooleanField(default=False)

    def __str__(self):
        return self.Provider_name


class Car_data(models.Model):
    Car = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Car


class Service_data(models.Model):
    Service = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Service

class Status_data(models.Model):
    Status = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Status


class Yeruka_data(models.Model):
    Yeruka = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Yeruka


class Yeruka2_data(models.Model):
    Yeruka2 = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Yeruka2


class To_data(models.Model):
    To = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.To


class From_data(models.Model):
    From = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.From


class Fields_to_cancel(models.Model):
    Currency_field = models.CharField(max_length=256, blank=True, unique=True)

    def __str__(self):
        return self.Currency_field

main/templates/main/Proj_form.html
{% extends 'main/pro_base.html' %}
{% load bootstrap %}
 
{% block title %}Project form{% endblock %}
 
{% block project %}
    <form method="post" role="form">
    <legend>Project Form</legend>
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

main/templates/main/base.html
{% extends 'main/pre_base.html' %}
{% block base %}

    <!-- Navigation -->
    {% include "main/top_navbar.html" %}

    {% if user.is_authenticated %}
        <p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
    {% else %}
        <p>Welcome, new user. Please Sign up.</p>
    {% endif %}
    <div class="container" id="transfer_list">
        {% block transfer_list %}
        {% endblock %}
        {% block login %}
        {% endblock %}
    </div>
    <!-- Masthead -->


    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2018. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-twitter fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
{% endblock %}

main/templates/main/customer_group.html
{% extends 'main/base.html' %}
{% block transfer_list %}

{% for e in error %}
<h1>{{e}}</h1>
{% endfor %}

<h3>project list</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>delete</th>
      {% for name in field_names %}
      <th>{{name}}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for row in customer_group %}

          <tr>
            <td><a href="/delete_transfer/{{transfer.id}}">{{ forloop.counter }}</a></td>
            <td>{{ row.Project_num}}</td>
            <td>{{ row.Customer}}</td>
            <td>{{ row.Date }}</td>
            <td>{{ row.Type_of_sevice}}</td>
            <td>{{ row.Type_of_car }}</td>
            <td>{{ row.Driver_name }}</td>
            <td>{{ row.Luggage }}</td>
            <td>{{ row.Name }}</td>
            <td>{{ row.Flight_num }}</td>
            <td>{{ row.Time_of_flight }}</td>
            <td>{{ row.Time_of_PU }}</td>
            <td>{{ row.End_time }}</td>
            <td>{{ row.From }}</td>
            <td>{{ row.To }}</td>
            <td>{{ row.Extra_hours_client }}</td>
            <td>{{ row.Based_on_client }}</td>
            <td>{{ row.Extra_hours_provider }}</td>
            <td>{{ row.Based_on_provider }}</td>
            <td>{{ row.KM }}</td>
            <td>{{ row.Comments }}</td>
            <td>{{ row.Provider }}</td>
            <td>{{ row.Cost_per_client }}</td>
            <td>{{ row.Cost_per_provider }}</td>
            <td>{{ row.Cost_extra_hour_client }}</td>
            <td>{{ row.Cost_extra_hour_provider }}</td>
            <td>{{ row.Cost_transfer_client }}</td>
            <td>{{ row.Cost_transfer_provider }}</td>
            <td>{{ row.Cost_VIP_client }}</td>
            <td>{{ row.Cost_VIP_provider }}</td>
            <td>{{ row.Status }}</td>


          </tr>

    {% endfor %}
  </tbody>
</table>

{% endblock %}

main/templates/main/date_time_widget.html
<div class="form-group">
    <div class='input-group date' id='datetimepicker1'>
        <input type='text' class="form-control" />
        <span class="input-group-addon">
            <span class="fa fa-calendar"></span>
        </span>
    </div>
</div>

main/templates/main/general_purpose_Modal.html
<div class="modal fade" id="general_purpose_Modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="m_title"></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>
            <div class="modal-body">
                <div id="m_body"></div>
                <select id="m_select">
                  <option  value="---SELECT---" selected="selected">---SELECT---</option>

                </select>
            </div>
            <div class="modal-footer">
                <div id="before_update_buttons" style="dispaly: none">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="">I understand</button>
                </div>
                <div id="update_buttons">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="dont_close_project()">no</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="close_project()">yes</button>
                </div>
            </div>
            <div id="last_val" style=""></div>
        </div>
    </div>
</div>

main/templates/main/index.html
{% extends 'main/pro_base.html' %}
{% load bootstrap %}
{% block transfer %}

            {% include 'main/bootstrap_form.html' %}

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
 {% endblock %}

main/templates/main/main_list_model_update_form.html
{% extends 'main/base.html' %}
{% block transfer_list %}

{% for e in error %}
<h1>{{e}}</h1>
{% endfor %}


<form action="" method="post" onsubmit="DoSubmit()" id="update_form">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

{% endblock %}

main/templates/main/pre_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Efi Caneti</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->

    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/landing-page.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/transfer_list.css' %}" rel="stylesheet">
    <link rel='stylesheet' href="{% static 'color_picker/spectrum.css' %}" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <!--<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css">-->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" rel="stylesheet"/>


    <!-- for date pick -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha18/css/tempusdominus-bootstrap-4.min.css" />
    <!--<link rel="stylesheet" href="{% static 'css/bs4-datetimepicker.min.css' %}" />-->
    <!--<script defer src="{% static 'js/fontawesome-all.js' %}"></script>-->
    <script defer src="{% static 'js/get_diff.js' %}"></script>

  </head>

  <body>

            {% block base %}
            {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'color_picker/spectrum.js' %}"></script>
    <!-- for date pick -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha18/js/tempusdominus-bootstrap-4.min.js"></script>
    <!--<script type="text/javascript" src="{% static 'js/bs4-datetimepicker.min.js' %}"></script>-->
    <script src="{% static 'js/table_colors.js' %}"></script>
            <!--<script src="{% static 'datatable/jquery.dataTables.min.js' %}"></script>-->
            <!--<script src="{% static 'datatable/dataTables.bootstrap4.min.js' %}"></script>-->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <!--<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
            <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
            <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
            <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>

            <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>-->
            <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.jss"></script>-->
            <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
            <script src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>
            <script src="https://cdn.datatables.net/plug-ins/1.10.15/dataRender/datetime.js"></script>

    <script defer src="{% static 'js/utility_functions.js' %}"></script>
    <script defer src="{% static 'js/dollar_shekel_euro.js' %}"></script>
    <script defer src="{% static 'js/table_filter.js' %}"></script>
    <script defer src="{% static 'js/status_and_km_function.js' %}"></script>
    <script defer src="{% static 'js/sum_and_maam.js' %}"></script>
    <script defer src="{% static 'js/csv_filter.js' %}"></script>
    <script defer src="{% static 'js/update_row.js' %}"></script>
    <script defer src="{% static 'js/cancle_turn_red.js' %}"></script>
    <script defer src="{% static 'js/ending_project.js' %}"></script>



   <script type="text/javascript">
        function display() {
            $('#settings').show()
        }

        function un_display() {
            $('#settings').hide()
        }

        $(function () {
            $('#datetimepicker1').datetimepicker({
              format: "dddd, MMMM DD YYYY"
            });
        });

        //https://stackoverflow.com/questions/41716125/set-min-date-in-bootstrap-datetimepicker-2
        //https://stackoverflow.com/questions/30891880/set-date-in-bootstrap-datetimepicker-input
        //https://momentjs.com/docs/

        $(function () {
            $('#Flight_shcedule').datetimepicker({
              format: 'YYYY-MM-DD HH:mm',
              useCurrent: false
            });
        });

        $(function () {
            $('#Start_time').datetimepicker({
              format: 'YYYY-MM-DD HH:mm',
              useCurrent: false
            });
        });

        $(function () {
            $('#End_time').datetimepicker({
              format: 'YYYY-MM-DD HH:mm',
              useCurrent: false
            });
        });

        $(function () {
            $('#start').datetimepicker({
              format: 'YYYY-MM-DD',
              useCurrent: false
            });
        });

        $(function () {
            $('#end').datetimepicker({
              format: 'YYYY-MM-DD',
              useCurrent: false
            });
        });

        $(function () {
            $('#new_date_time').datetimepicker({
              format: 'YYYY-MM-DD HH:mm',
              useCurrent: false
            });
        });

        $(function () {
            $('#new_date').datetimepicker({
              format: "YYYY-MM-DD",
              useCurrent: false
            });
        });

        $(function () {
            $('#flight_shcedule_update').datetimepicker({
              format: 'HH:mm',
              useCurrent: false
            });
        });


        $("#custom").spectrum({
          preferredFormat: "rgb",
        });

        //$(document).ready(function() {
        //    $('#mainlist').DataTable();
        //} );

        $(document).ready(function() {

            $('#id_To').select2({
              tags: true,
              placeholder: "Select",
            });
            $('#id_Flight_num').select2({
              tags: true,
              placeholder: "Select",
            });
            $('#id_Driver_name').select2({
              tags: true,
              placeholder: "Select",
            });
            $('#id_Provider').select2({
              tags: true,
              placeholder: "Select",
            });
            $('#id_From').select2({
              tags: true,
              placeholder: "Select",
            });
        });

        //$("#id_Flight_num").val('---')


    </script>

  </body>

</html>

main/templates/main/project.html
{% extends 'main/pro_base.html' %}
{% load bootstrap %}
 
{% block title %}Project{% endblock %}
 
{% block project %}
    <form role="form">
    <legend>Project Form</legend>
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

main/templates/main/send_tables.html
{% load staticfiles %}
{% autoescape off %}
{{test}}
<h3>main list</h3>
{{mainlist}}
<h3>sum list</h3>
{{sum_list}}
{% endautoescape %}

main/templates/main/table_view.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>List of persons</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />-->
        <link rel='stylesheet' href="{% static 'color_picker/spectrum.css' %}" />
    </head>
    <body>
    <input type='text' id="custom" />

    <label>תצוגת כתב</label>
    <input type="checkbox" id="color_method">

    <br>
    {% render_table table %}


    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'color_picker/spectrum.js' %}"></script>
    <script src="{% static 'js/table_colors.js' %}"></script>


   <script type="text/javascript">

   $("#custom").spectrum({
          preferredFormat: "rgb",
    });


    </script>
    </body>
</html>